---
project_name: opentofu

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - make protobuf

builds:
  - env:
      - CGO_ENABLED=0

    flags:
      - "-mod=readonly"
      - "-trimpath"

    ldflags:
      - "-s -w"
      - "-X 'github.com/opentofu/opentofu/version.dev=no'"

    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
      - solaris

    goarch:
      - "386"
      - amd64
      - arm
      - arm64

    ignore:
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: "386"
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{- .Os }}_{{- .Arch }}"

dockers:
  - use: buildx
    goarch: amd64
    build_flag_templates: &default-container-labels
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.vendor=OpenTofu"
      - "--label=org.opencontainers.image.description=OpenTofu {{ .Version }}"
      - "--label=org.opencontainers.image.url=https://github.com/opentofu/opentofu"
      - "--label=org.opencontainers.image.documentation=https://github.com/opentofu/opentofu/blob/main/README.md"
      - "--label=org.opencontainers.image.source=https://github.com/opentofu/opentofu"
      - "--label=org.opencontainers.image.licenses=MPL-2.0"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ time \"2006-01-02T15:04:05Z07:00\" }}"
    image_templates:
      - "ghcr.io/opentofu/opentofu:{{ .Version }}-amd64"

  - use: buildx
    goarch: arm64
    build_flag_templates: *default-container-labels
    image_templates:
      - "ghcr.io/opentofu/opentofu:{{ .Version }}-arm64"

  - use: buildx
    goarch: arm
    build_flag_templates: *default-container-labels
    image_templates:
      - "ghcr.io/opentofu/opentofu:{{ .Version }}-arm"

  - use: buildx
    goarch: "386"
    build_flag_templates: *default-container-labels
    image_templates:
      - "ghcr.io/opentofu/opentofu:{{ .Version }}-386"

docker_manifests:
  - name_template: ghcr.io/opentofu/opentofu:v{{ .Version }}
    image_templates: &default-image-templates
      - ghcr.io/opentofu/opentofu:{{ .Version }}-amd64
      - ghcr.io/opentofu/opentofu:{{ .Version }}-arm64
      - ghcr.io/opentofu/opentofu:{{ .Version }}-arm
      - ghcr.io/opentofu/opentofu:{{ .Version }}-386

  - name_template: ghcr.io/opentofu/opentofu:{{ .Major }}
    image_templates: *default-image-templates

  - name_template: ghcr.io/opentofu/opentofu:{{ .Major }}.{{ .Minor }}
    image_templates: *default-image-templates

  - name_template: ghcr.io/opentofu/opentofu:latest
    image_templates: *default-image-templates

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  use: github-native

release:
  draft: true
