
name: 'Setup go toolchain'
description: 'Sets up the go toolchain ato use for any go related actions'
runs:
  using: composite
  steps:
  - name: Install Go toolchain
    uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
    with:
      go-version-file: 'go.mod'
