# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: '3.8'
services:
  website:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ../:/work/opentofu-repo
    command:
      - npm
      - run
      - build
    restart: no