name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened']

jobs:
  title:
    name: Description Validation
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run fabiankoestring/body-regex-validator-action
        uses: fabiankoestring/body-regex-validator-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_PATTERN: '^(.*Resolves.*)$'
          PULL_REQUEST_COMMENT: 'This is my pr comment template.'