name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: Description Validation
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get description
        run: |
          body=$(gh pr view --json body --jq ".body" ${{ github.event.pull_request.head.ref }})
          pattern='\bResolves\s+#\d+\b'
          if echo "$body" | grep -P -q "$pattern"; then
            exit 0
          else
            exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}