name: Pull Request Lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  title:
    name: Description Validation
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get description
        run: |
          gh pr view --json body --jq ".body" ${{ github.event.pull_request.base.ref }}
        env:
          GH_TOKEN: ${{ github.token }}