name: Validate Pull Request Description
on:
  pull_request:

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    steps:
      - name: Run actions/checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Run fabiankoestring/body-regex-validator-action
        uses: fabiankoestring/body-regex-validator-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_PATTERN: '^(.*Resolves #\d+)$'
          PULL_REQUEST_COMMENT: 'This is my pr comment template.'